name: PR Builder for EmotePlugin

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-2022

    env:
      Solution_Name: EmotePlugin

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Prepare Environment
      uses: xivdev/Penumbra/.github/actions/prepare-environment@master
      with:
        project: EmotePlugin

    - name: Build and Upload Artifact
      uses: xivdev/Penumbra/.github/actions/build-with-artifact@master
      with:
        configuration: Release
        project: EmotePlugin

